pipeline {
    agent any

    stages {
        stage('git pull') {
            steps {
                git branch: 'main', url: 'https://github.com/Mraakhil/s3terraform.git
            }
        }
    }
    stage('Init') {
            steps {
                    sh 'terraform init'
                }
            }
        

    
}
